### ISSUE TITLE
build el7 rpm for foreman_custom_banner

### ISSUE THREAD

**Issue by lawre** [jcmcken/foreman_custom_banner#2]
For the non-ruby user like myself, could you please build an el7 rpm that can be installed with a simple 'yum install ruby193-rubygem-foreman_custom_banner' from the foreman repo?

I have spend the last 2 hours trying to get this installed using various tutorials around the web and am unable to find a clear and concise way to get this plugin installed, and I am way out of depth trying to diagnose ruby related issues.  Thanks.

**Comment by jcmcken** [comment]
Hi, sorry for the late reply. I'm not sure I want to provide you an RPM, but I could possibly make it easier to build yourself (e.g. with a `Makefile`). I'll look into it, but not promising anything. I haven't played with EL7 too much yet so not sure if there's anything special I'd need to do, but I can at least see if it works

**Comment by domcleal** [comment]
If you'd like to get this into Foreman's plugins repo we could do that, making it available for all of our supported OSes - including Debian if somebody wanted to package it.

The best way to start would be to push your current (0.0.2) release to rubygems.org, then we can package it over in foreman-packaging using your current spec file or one of ours as a template (https://github.com/theforeman/foreman-packaging/tree/rpm/develop#readme).  EL7 should be identical to EL6 as both use SCL and so they're identical.

**Comment by jcmcken** [comment]
I'll push up the updated gem later today and close out this issue. Sorry for the delay

**Comment by jcmcken** [comment]
I pushed up 0.0.2 to rubygems.org and reset the Github 0.0.2 release to version containing the updated license. Let me know if there's anything else

**Comment by jcmcken** [comment]
I'm going to go ahead and close this, with the hope that plugin gets included in the official repo(s). In any case, I don't have plans to host any packages myself. @lawre if you're still having issues, maybe submit to the Foreman users group? A couple of people are using this plugin in production using the Foreman-provided packages, so it's probably just a matter of configuring things correctly

**Comment by mmoll** [comment]
If anybody would open a RPM PR to the foreman-packaging repo, I'd do one for DEB.
(context: http://projects.theforeman.org/issues/8259)
