### ISSUE TITLE
Hyperlink in Custom Banner

### ISSUE THREAD

**Issue by discreet** [jcmcken/foreman_custom_banner#4]
It would be cool if one had the ability to have a hyperlink in the Custom Banner which can link to a "help" page or "quick start guide" for the specific foreman instance.

**Comment by jcmcken** [comment]
Is there a particular way you'd like the banner to be formatted? E.g. a thicker banner with the hyperlink below the text? Use the text as the link text?

**Comment by discreet** [comment]
@jcmcken I forked the repo and worked out all of what I wanted. It has been tested against Foreman 1.10, 1.11 and 1.12-develop. I can submit a PR for your review if you'd like.

**Comment by jcmcken** [comment]
Sure

**Comment by discreet** [comment]
@jcmcken PR submitted
