### ISSUE TITLE
Incompatible with newer Forman Versions

### ISSUE THREAD

**Issue by PhilippvK** [jcmcken/foreman_custom_banner#8]
As far as I was able to test, the banner is only visible on the Foreman Login Page with Foreman v1.17+. No Banner on other Foreman-Sites.

The reason for this seems to be the new Interface with the vertical sidebar,... 

If this is unmaintained, I will probably look into it but not in the next few weeks.

**Comment by jcmcken** [comment]
I maintained this plugin as a part of a previous job. Would be willing to transfer/donate it to the Foreman project if they'll accept it. I'm not sure about transferring it to someone I don't know, though, but feel free to fork

**Comment by PhilippvK** [comment]
Hey, thank you for your answer.

Do do not think, that I would be able to maintain the project. Sorry, if that's what it sounded like.

I justed wanted to document the Issue, so that other people who want to use the plugin are aware of this.

Maintenance by the foreman team sound great but thats your decision.

**Comment by wackysysadmin** [comment]
As of version 3.10 Foreman now includes a banner built in. It can be configured via Settings -> "Instance title" and "Instance color" which can have text and a colour hex set accordingly.

https://community.theforeman.org/t/rfc-adding-banner-to-distinguish-multiple-foreman-instances/34133
https://projects.theforeman.org/issues/36872

<img width="214" alt="image" src="https://github.com/jcmcken/foreman_custom_banner/assets/1969608/7086b732-1d6a-495e-8e01-b74d6258c6e9">
